import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Storybook's static build output (generated by `build-storybook`).
    "storybook-static/**",
  ]),
  // shadcn-generated files are vendored verbatim via the CLI and must not be
  // hand-edited (see CLAUDE.md). They legitimately sync initial state inside an
  // effect, which trips react-hooks/set-state-in-effect — disable it for them.
  {
    files: ["src/components/ui/**/*.{ts,tsx}", "src/hooks/use-mobile.ts"],
    rules: {
      "react-hooks/set-state-in-effect": "off",
    },
  },
]);

export default eslintConfig;
